### ISSUE TITLE
Button 308 Reset Shortcuts Error

### ISSUE THREAD

**Issue by mikesilvo164** [mikesilvo164/script.skinshortcuts#65]
@anxdpanic Been doing some testing and ran into a bug.
```ERROR <general>: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: 'DataFunctions' object has no attribute 'labelIDList'
Traceback (most recent call last):
 File "C:\Users\mikes\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\skinshorcuts\gui.py", line 1472, in onClick
original_label_id_list = self.data_func.labelIDList
AttributeError: 'DataFunctions' object has no attribute 'labelIDList'
-->End of Python script error report<--```

Full Debug Log [HERE](https://paste.kodi.tv/cibuqadixi.kodi)

Thanks again for the work on the script! Don't understand most of it lol

**Comment by anxdpanic** [comment]
Thanks for testing, and I'm happy to do it!
Should be fixed with https://github.com/mikesilvo164/script.skinshortcuts/pull/66/commits/153fae44c9c87ef5141418e3aff24aad9533b332
New zip available at https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.0.alpha8

In case you're curious, about a before an after snapshot. 
Beyond removing duplicates and refactoring to simplify stuff, these are the before and after numbers from an inspection with a Python IDE.

Before: https://snipboard.io/mv2dAr.jpg
After: 0 across the board 😄
